apiVersion: v1
kind: Secret
metadata:
  name: image-secret
  namespace: gfandada
  annotations:
    tekton.dev/docker-0: <your-docker-registry>
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext non-encoded>
  password: <cleartext non-encoded>
