apiVersion: v1
kind: Secret
metadata:
  name: image-secret
  annotations:
    tekton.dev/docker-0: https://registry.cn-chengdu.aliyuncs.com
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext non-encoded>
  password: <cleartext non-encoded>
