---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: gfandada
secrets:
  - name: image-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  namespace: gfandada
  annotations:
    kubernetes.io/service-account.name: pipeline-account
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
  namespace: gfandada
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: gfandada
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
  namespace: gfandada
subjects:
  - kind: ServiceAccount
    name: pipeline-account
    namespace: gfandada